name: to_do_app
description: "A simple ToDo Application developed using Flutter & Clean Architecture"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  url_launcher: ^6.3.0
  firebase_auth: ^5.1.3
  firebase_core: ^3.3.0
  firebase_ui_auth: ^1.15.0
  cloud_firestore: ^5.2.0
  cached_network_image: ^3.4.0
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_riverpod: ^2.5.1
  get_it: ^7.7.0
  shared_preferences: ^2.3.1
  loader_overlay: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  very_good_analysis: ^6.0.0

flutter:

  uses-material-design: true